export const FETCH_PLAYLISTS_SEARCH_START = 'FETCH_PLAYLISTS_SEARCH_START';
export const FETCH_PLAYLISTS_SEARCH_SUCCESS = 'FETCH_PLAYLISTS_SEARCH_SUCCESS';
export const FETCH_PLAYLISTS_SEARCH_FAILURE = 'FETCH_PLAYLISTS_SEARCH_FAILURE';

export const FETCH_VIDEOS_SEARCH_START = 'FETCH_VIDEOS_SEARCH_START';
export const FETCH_VIDEOS_SEARCH_SUCCESS = 'FETCH_VIDEOS_SEARCH_SUCCESS';
export const FETCH_VIDEOS_SEARCH_FAILURE = 'FETCH_VIDEOS_SEARCH_FAILURE';

export const CLEAR_PLAYLISTS_SEARCH_RESULTS = 'CLEAR_PLAYLISTS_SEARCH_RESULTS';
export const CLEAR_VIDEOS_SEARCH_RESULTS = 'CLEAR_VIDEOS_SEARCH_RESULTS';