export const FETCH_TOP_PLAYLISTS = 'FETCH_TOP_PLAYLISTS';
export const FETCH_TOP_PLAYLISTS_SUCCESS = 'FETCH_TOP_PLAYLISTS_SUCCESS';

export const SET_CURRENT_PLAYLIST = 'SET_CURRENT_PLAYLIST';

export const ADD_VIDEO = 'ADD_VIDEO';
export const ADD_VIDEO_TO_CURRENT_PLAYLIST = 'ADD_VIDEO_TO_CURRENT_PLAYLIST';

export const TOGGLE_LIKE = 'TOGGLE_LIKE';
export const TOGGLE_LIKE_WITH_CURRENT_USER = 'TOGGLE_LIKE_WITH_CURRENT_USER';

export const REMOVE_VIDEO_FROM_CURRENT_PLAYLIST = 'REMOVE_VIDEO_FROM_CURRENT_PLAYLIST';