export const CONNECT_TO_SOCKET = 'CONNECT_TO_SOCKET';

export const VIDEO_ADDED_VIA_SOCKET = 'VIDEO_ADDED_VIA_SOCKET';
export const VIDEO_REMOVED_VIA_SOCKET = 'VIDEO_REMOVED_VIA_SOCKET';
export const LIKE_TOGGLED_VIA_SOCKET = 'LIKE_TOGGLED_VIA_SOCKET';