export const GOOGLE_SIGN_IN = 'GOOGLE_SIGN_IN';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';

export const SIGN_OUT = 'SIGN_OUT';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
export const SIGN_OUT_FAILURE = 'SIGN_OUT_FAILURE';

export const CHECK_USER_SESSION = 'CHECK_USER_SESSION';
export const CHECK_USER_SESSION_START = 'CHECK_USER_SESSION_START';
export const CHECK_USER_SESSION_END = 'CHECK_USER_SESSION_END';