export const CONNECT_TO_SOCKET = 'CONNECT_TO_SOCKET';

export const VIDEO_SET_PLAY = 'VIDEO_SET_PLAY';
export const VIDEO_SET_PAUSE = 'VIDEO_SET_PAUSE';

export const VIDEO_PLAYED_VIA_SOCKET = 'VIDEO_PLAYED_VIA_SOCKET';
export const VIDEO_PAUSED_VIA_SOCKET = 'VIDEO_PAUSED_VIA_SOCKET';