export const FETCH_TOP_VIDEOS = 'FETCH_TOP_VIDEOS';
export const FETCH_TOP_VIDEOS_SUCCESS = 'FETCH_TOP_VIDEOS_SUCCESS';

export const FETCH_VIDEOS = 'FETCH_VIDEOS';
export const FETCH_VIDEOS_SUCCESS = 'FETCH_VIDEOS_SUCCESS';

export const VIDEO_SET_PLAY = 'VIDEO_SET_PLAY';
export const VIDEO_SET_PAUSE = 'VIDEO_SET_PAUSE';

export const VIDEO_PLAYED_VIA_SOCKET = 'VIDEO_PLAYED_VIA_SOCKET';
export const VIDEO_PAUSED_VIA_SOCKET = 'VIDEO_PAUSED_VIA_SOCKET';